spring:
  application:
    name: mongodemo
  data:
    mongodb:
      username: tdz93
      password: tdz93
      host: localhost
      port: 27017
      database: mongodemo
      authentication-database: admin

server:
  port: 9000